# Generated by Django 3.2.4 on 2021-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UspsServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=1000)),
                ('serviceDescription', models.TextField()),
                ('accessFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
